### PR TITLE
add enumext compatibility

### PR DESCRIPTION
**Pull request by mbertucci47**
Lists [enumext](https://www.ctan.org/pkg/enumext) as compatible and adds several tests. The tests were kindly provided by @pablgonz as part of the documentation. The package hand-tunes the tagging so it would probably be good if someone else took a look at this too.

### CODE REVIEW

**Comment by FrankMittelbach** [comment]
I'm not 100% percent sure about the generated tagging. It  doesn't look wrong, but there are some aspect that I think aren't quite right (or intended).  For example, if there is text directly in front of a list (not in your exaple but one could change that) then I would expect that text + the list becoming part of a single `<text-unit>` consisting of `<text>` followed by `<list>`  but instead one gets always two `<text-unit>`s, which implies that there is an empty line before the list.  For example


Screenshot 2024-11-13 at 17 38 08


 I also saw some `<Div>` which I don't see why they appear, e.g.,  here:

Screenshot 2024-11-13 at 17 34 46

comments @u-fischer, @pablgonz ?

**Comment by u-fischer** [comment]
@FrankMittelbach I can not reproduce your output. The tagging looks ok. Can you show the file you compiled and the log-file?

**Comment by pablgonz** [comment]
@FrankMittelbach @u-fischer Hi, first of all thanks for taking the time to look, I did the comparison tests using the standard `enumerate` environment provided by LaTeX, my version of Acrobat DC is quite old so I don't see the same output, but with `ngpdf` the comparison is the same.

```latex
\DocumentMetadata
  {
    lang=en-US,
    pdfversion=2.0,
    pdfstandard=ua-2,
    testphase={phase-III,math,title,table,firstaid},
    uncompress,
  }
\documentclass{article}
\usepackage[top=2cm,bottom=2cm,left=1cm,right=1cm]{geometry}
\usepackage{unicode-math,hyperref,enumext}
\hypersetup
  {
    colorlinks = true,
    pdftitle   = {Test tagged PDF for enumext package},
  }
\begin{document}
\section{only enumext}
Some text here \begin{enumext}[labelwidth=1cm,labelsep=0.25cm,align=left, wrap-label=\textbf{(#1}, label=\arabic*.)]
  \item This text is in the first level.\label{A}
    \begin{enumext}
      \item This text is in the second level.\footnote{foot note in enumext}
        \begin{enumext}
          \item This text is in the third level.
            \begin{enumext}
              \item This text is in the fourth level.\footnotemark[20]
            \end{enumext}
        \end{enumext}
    \end{enumext}
  \item[X] This text is in the first level.
  \item* This text is in the first level.
\end{enumext}

Some ref here \ref{A}\footnotetext[20]{foot note in enumext [20]}

\end{document}
```
enumext-ngpdf

```latex
\DocumentMetadata
  {
    lang=en-US,
    pdfversion=2.0,
    pdfstandard=ua-2,
    testphase={phase-III,math,title,table,firstaid},
    uncompress,
  }
\documentclass{article}
\usepackage[top=2cm,bottom=2cm,left=1cm,right=1cm]{geometry}
\usepackage{unicode-math,hyperref,enumext}
\hypersetup
  {
    colorlinks = true,
    pdftitle   = {Test tagged PDF for standar enumerate},
  }
\begin{document}
\section{only enumerate}
Some text here \begin{enumerate}
  \item This text is in the first level.\label{A}
    \begin{enumerate}
      \item This text is in the second level.\footnote{foot note in enumext}
        \begin{enumerate}
          \item This text is in the third level.
            \begin{enumerate}
              \item This text is in the fourth level.\footnotemark[20]
            \end{enumerate}
        \end{enumerate}
    \end{enumerate}
  \item[X] This text is in the first level.
  \item* This text is in the first level.
\end{enumerate}

Some ref here \ref{A}\footnotetext[20]{foot note in enumext [20]}

\end{document}
```
enumerate-standar-ngpdf

For the second question regarding `<DIV>`, the comparison (due to the implementation of `enumext*`) is as follows:

```
\DocumentMetadata
  {
    lang=en-US,
    pdfversion=2.0,
    pdfstandard=ua-2,
    testphase={phase-III,math,title,table,firstaid},
    uncompress,
  }
\documentclass{article}
\usepackage[top=2cm,bottom=2cm,left=1cm,right=1cm]{geometry}
\usepackage{unicode-math,hyperref,enumext}
\hypersetup
  {
    colorlinks = true,
    pdftitle   = {Test tagged PDF for enumerate+minipage},
  }
\begin{document}
\section{only enumerate}
Some text here

\begin{enumerate}
  \item \begin{minipage}[t]{\dimeval{\linewidth-\labelwidth-\labelsep}} This text is in the first level. \end{minipage}
  \item[X] \begin{minipage}[t]{\dimeval{\linewidth-\labelwidth-\labelsep}} This text is in the first level. \end{minipage}
\end{enumerate}

\section{only enumext*}
Some text here

\begin{enumext*}
  \item This text is in the first level.
  \item[X] This text is in the first level.
\end{enumext*}

\end{document}
```

enumerate-starred-minipage-ngpdf

**Comment by FrankMittelbach** [comment]
> @FrankMittelbach I can not reproduce your output. The tagging looks ok. Can you show the file you compiled and the log-file?

sorry, I confused myself. I put the `%`in front of the second list but then looked at the first, mea culpa. However looking at the output, the reason I guess I did this was, that the spacing between the test and the first list is shorter than the one between the text and the second, which I took as a sign that the first list is part of the same paragrap. However, that spacing differenceseems to be just a difference between enumext and exnumext* (not sure it is deliberate, but it has nothing to do with tagging). So yes, tagging is fine and thanks for the explanation where the Div comes from.

**Comment by pablgonz** [comment]
> > @FrankMittelbach I can not reproduce your output. The tagging looks ok. Can you show the file you compiled and the log-file?
> 
> sorry, I confused myself. I put the `%`in front of the second list but then looked at the first, mea culpa. However looking at the output, the reason I guess I did this was, that the spacing between the text and the first list is shorter than the one between the text and the second, which I took as a sign that the first list is part of the same paragraph. However, that spacing difference seems to be just a difference between enumext and exnumext* (not sure it is deliberate, but it has nothing to do with tagging). So yes, tagging is fine and thanks for the explanation where the Div comes from.

Thanks, you found a problem in my implementation of the `base-fix` key, the behavior of the `enumext*` environment is correct (and the standard when `topsep` is not equal to `0pt`), it is already fixed (along with many other things) for the next version.
Thanks for everything
Saludos

**Pull request merged**
