### PR TITLE
add cancel compatibility

### PR DESCRIPTION
**Pull request by mbertucci47**
Lists [cancel](https://www.ctan.org/pkg/cancel) as "compatible" with the math comment and adds a test file.

### CODE REVIEW

**Comment by davidcarlisle** [comment]
I'm not sure this should be marked as compatible, even if we defer the math use to a better mathml generator to be applied, the text use of `\xcancel{blub}`  gets tagged as text `)))blub`  which I guess is sub-optimal (not sure how a strikeout should be tagged) @u-fischer ?

**Comment by u-fischer** [comment]
I agree with @davidcarlisle. I'm not sure how the math/mathml should look like, but the text version should imho be tagged with a Span + a TextDecorationType attribute with value LineThrough.

**Comment by davidcarlisle** [comment]
so I think this needs to be `currently-incompatible` as even if it doesn't error the tagging is actively misleading as it loses the fact that the text is crossed out

**Comment by mbertucci47** [comment]
Status has been updated with a comment

**Pull request merged**
