### PR TITLE
add amsrefs compatibility

### PR DESCRIPTION
**Pull request by mbertucci47**
Lists amsrefs as compatible and adds a few tests.

### CODE REVIEW

**Comment by davidcarlisle** [comment]
the references get tagged as a list but shouldn't specific bibliography tagging get used @u-fischer @FrankMittelbach ?

**Comment by mbertucci47** [comment]
@davidcarlisle I haven't looked into the code but a simple example doesn't show any bibliography specific tagging.
```tex
\DocumentMetadata
  {
    lang=en-US,
    pdfversion=2.0,
    pdfstandard=ua-2,
    testphase={phase-III,math,title,table,firstaid},
  }
\documentclass{article}

\begin{document}

Some text and a citation: \cite{inbook-full}

\bibliographystyle{amsalpha}
\bibliography{xampl}

\end{document}
```

**Comment by davidcarlisle** [comment]
I'll leave this one for the others to review but note there is additional bib code in testphase={bib}, (I think)

**Comment by u-fischer** [comment]
@davidcarlisle there is currently no special code for the bibliography - it is still open if there is a need to use Bibentry somewhere or if a list as we use now is enough. The main point of the bib code is to ensure that there is a reference from the citation to the bib.

**Comment by davidcarlisle** [comment]
ah OK, so I'll merge thanks

**Comment by FrankMittelbach** [comment]
@davidcarlisle @u-fischer I stll wonder if we shouldn't at least add in cases like this a `tasks=review when ...` because if there is a decision to make them up differently the package would need an update.

**Comment by davidcarlisle** [comment]
@FrankMittelbach  yes I added a comment in `tasks`

**Pull request merged**
