### PR TITLE
TLC3 recommended packages (letter A)

### PR DESCRIPTION
**Pull request by FrankMittelbach**

### CODE REVIEW

**Comment by FrankMittelbach** [comment]
perhaps a few more could me marked compatible (just by the look of it)

**Review by davidcarlisle — APPROVED** [review]
I'll merge, some may need ctan-pkg adding (unless you checked this already)  but that can be added later

**Comment by davidcarlisle** [comment]
actually these:

```
amssymb
antpolt
anttor
apalike
authordate1-4
avant
```

**Comment by davidcarlisle** [comment]
ctan-pkg added at 874590a

**Pull request merged**
