### PR TITLE
add dashrule compatibility

### PR DESCRIPTION
**Pull request by mbertucci47**
Lists [dashrule](https://ctan.org/pkg/dashrule) as compatible and adds a test. I'm not sure about this one because the rule commands appear as "Path" or worse "PathPathPath..." in tags, however this is also the behavior of `\rule`. Maybe these should be Artifacts? But then the same should be true for `\rule`.

### CODE REVIEW

**Comment by u-fischer** [comment]
rules should normally be artifacts unless they have some semantic meaning, in which case they should be a span with actual text.

**Comment by mbertucci47** [comment]
Okay, I will change the status then. Does this mean the tagging for `\rule` should be changed too? I encounter similar issues with "PathPath..." a lot with things like `\fbox{text}` too where I don't know what the correct tagging should be.

**Comment by mbertucci47** [comment]
Status changed to partially-compatible

**Comment by FrankMittelbach** [comment]
> Okay, I will change the status then. Does this mean the tagging for `\rule` should be changed too? I encounter similar issues with "PathPath..." a lot with things like `\fbox{text}` too where I don't know what the correct tagging should be.

I think one way to say this is that `\fbox` in core LaTeX is not handled correctly and should perhaps get its own issue.

**Review by FrankMittelbach — APPROVED** [review]

**Comment by u-fischer** [comment]
>  Does this mean the tagging for \rule should be changed too? 

Yes. It would naturally be easier if one could simply leave them alone, but in the end we will have to review various uses of rules (also in tabulars etc).

**Comment by mbertucci47** [comment]
See #420

**Pull request merged**
