### PR TITLE
add afterpage compatibility

### PR DESCRIPTION
**Pull request by mbertucci47**
Lists afterpage as compatible and includes a test file. The tagging seems to appear in the correct place

### CODE REVIEW

**Comment by davidcarlisle** [comment]
I agree that the supplied test file looks OK, but given what `afterpage` does I'd be astonished if it manages to be compatible here in general (since I have not done anything to make it compatible).  In the test file there is nothing much happening at the end of page so the afterpage insertion happens at a relatively safe place, but in general the insertion can happen within an arbitrary structure, say mid list, or between the lines of a math `align`  or (my personal favourite between the first and second `$` in `$$`  (so after math mode detected but before a display math starts)  It seems unlikely that inserting in these places does not mess up the tag nesting, but I'll try to make an example.

**Comment by davidcarlisle** [comment]
I think the test is fine and shows it doesn't completely break, but I think `partially-compatible` with a comment more tests needed would be a safer status than claiming compatibility.

**Comment by mbertucci47** [comment]
@davidcarlisle Suggested changes added

**Comment by FrankMittelbach** [comment]
I was about to say the same, one should really take a look through usages of afterpage in TL and build matching use cases. However, it isn't that unlikely that it works out of the box in most cases if not in all.

**Pull request merged**
