### PR TITLE
add parskip compatibility

### PR DESCRIPTION
**Pull request by mbertucci47**
Lists parskip as compatible and adds a test file.

### CODE REVIEW

**Review by FrankMittelbach — CHANGES_REQUESTED** [review]
Why was this made prio 9 at some point?  This is a TLC3 package so no prio or prio 1 please

**Comment by davidcarlisle** [comment]
@FrankMittelbach  that may have been me, adding the initial priorities basically ran off update date, so if a packge was updated after the main addition of tlc3 it may have been wrongly priotised. priority is ignored for `compatible` packages in any case so it can be deleted.

**Comment by mbertucci47** [comment]
Wasn't me :) Fixed

**Comment by FrankMittelbach** [comment]
> Wasn't me :) Fixed

:-) didn't meant to indicate that

**Pull request merged**
