### PR TITLE
add tabulary compatibility

### PR DESCRIPTION
**Pull request by mbertucci47**
Lists tabulary as "compatible", supported with phase-III and table. Test file added; examples from documentation.

### CODE REVIEW

**Comment by FrankMittelbach** [comment]
With other table packages \hline and \cline are often causing issues, wonder if those should be added to the test(s)

**Comment by mbertucci47** [comment]
@FrankMittelbach Yes it seems `\hline` works but `\cline` causes issues. I will adjust

**Comment by davidcarlisle** [comment]
@FrankMittelbach  depends how we view it. Unlike say `longtable`, `tabulary` does not touch `\hline`/`\cline` at all so that is just array package code. The package does have (since the release last week) explicit tagging support to guard its trial runs. So not sure if cline issues should mark every table package failing here.

**Comment by FrankMittelbach** [comment]
Well, if we overlooked \cline for array, then we should build some tests to show that this is failing and mark it as partially-compatible (and actually fix it asap)

**Comment by davidcarlisle** [comment]
@mbertucci47  the cline issue you spotted, does the same appear if you just use a tabular with the `array` package?

**Comment by mbertucci47** [comment]
@davidcarlisle Yes, for example
```
\begin{tabular}{crl}
A & B & D \\ \cline{1-2}
E & F & G
\end{tabular}
```
errors

**Comment by davidcarlisle** [comment]
thanks, that also fails without `array`

```
\DocumentMetadata{
  testphase={phase-III,table}
}
\documentclass{article}

\begin{document}

\begin{tabular}{crl}
A & B & D \\ \cline{1-2}
E & F & G
\end{tabular}
\end{document}

```

so I guess we should fix in the latex-lab `table` support rather than flag the individual packages.

**Comment by mbertucci47** [comment]
@davidcarlisle Doesn't the table tagging code automatically load array?

**Comment by davidcarlisle** [comment]
> @davidcarlisle Doesn't the table tagging code automatically load array?

er yes, so strike my "fails without array" comment, (but still means we need to fix this in the generic latex-lab table code not specific for this package)

**Comment by u-fischer** [comment]
looks as if we completly forgot \cline, there is neither code nor testfiles.
Something like this avoid the error. Additionally some tagging code is needed to artifact the leader

~~~~
\DocumentMetadata
  {
    lang=en-US,
    pdfversion=2.0,
    pdfstandard=ua-2,
    testphase={phase-III,math,title,table,firstaid},
    uncompress
  }
\documentclass{article}
\makeatletter\ExplSyntaxOn
\def\@cline#1-#2\@nil{%
  \omit
  \@multicnt#1%
  \advance\@multispan\m@ne
  \ifnum\@multicnt=\@ne\@firstofone{&\omit}\fi
  \@multicnt#2%
  \advance\@multicnt-#1%
  \advance\@multispan\@ne
  \leaders\hrule\@height\arrayrulewidth\hfill %artifact tagging needed
  \tbl_gdecr_row_count: %<----------------
  \cr
  \noalign{\vskip-\arrayrulewidth}}
\ExplSyntaxOff
\usepackage{tabulary}

\begin{document}
\begin{tabular}{crl}
A & B & D \\ \cline{1-2}
E & F & G
\end{tabular}
\end{document}
~~~~

**Comment by davidcarlisle** [comment]
@u-fischer  thanks, so we merge this pr as is and handle that elsewhere?

**Comment by u-fischer** [comment]
@davidcarlisle  yes, I just opened an issue for this.

**Pull request merged**
