### PR TITLE
add topcapt compatibility

### PR DESCRIPTION
**Pull request by mbertucci47**
Lists [topcapt](https://www.ctan.org/pkg/topcapt) as compatible and adds a test file.

### CODE REVIEW

**Comment by davidcarlisle** [comment]
Not sure this should be `compatible` it doesn't error but the caption is essentially just text I think, the extensive \caption support in

latex2e/required/latex-lab/latex-lab-float.dtx

isn't picked up as `\topcaption` is just a modified copy of the original caption code, it doesn't actually use any of the redefined caption code.

% \subsection{Handling captions}

**Comment by mbertucci47** [comment]
In Acrobat it seems to be tagged the same as with `\caption`. Here's the tags from the example:

topcapt_struc

The first is with `\topcaption`, the second with `\caption`. I think `\topcaption` is just using an unmodified `\@caption` so still picks up the tagging code

**Comment by davidcarlisle** [comment]
oh I must have missed something sorry, I'll re-check

**Comment by davidcarlisle** [comment]
@mbertucci47  I misread the package code...

**Pull request merged**
