### PR TITLE
TLC3 packages (I-M)

### PR DESCRIPTION
**Pull request by FrankMittelbach**

### CODE REVIEW

**Review by davidcarlisle — APPROVED** [review]

**Comment by davidcarlisle** [comment]
@FrankMittelbach  I added two ctan-pkg at 9645c86  but I couldn't find `literat` ?

**Comment by FrankMittelbach** [comment]
> @FrankMittelbach I added two ctan-pkg at [9645c86](https://github.com/latex3/tagging-project/commit/9645c867b64356539fdd24a15ef4bdcdf57583d8) but I couldn't find `literat` ?

TLC3 says:

The fonts are not part of the standard distributions but can be installed with getnonfreefonts.

**Comment by davidcarlisle** [comment]
ah fonts, found it https://ctan.org/pkg/literaturnaya

**Comment by davidcarlisle** [comment]
2f970c7

**Pull request merged**
