### PR TITLE
devanagari not devnag package

### PR DESCRIPTION
**Pull request by davidcarlisle**
devnag is the preprocessor name not a package or class: changed entry to devanagari

### CODE REVIEW

**Review by FrankMittelbach — COMMENTED** [review]
I wonder if we shouldn't just drop them. The reference in TLC3 is just to old 8-bit engine support which for such languages is at best suboptimal. So I doubt it will ever get a status anyway. Same for bengali then. Ref is TLC3 II-341

**Comment by davidcarlisle** [comment]
@FrankMittelbach  OK wth me, I can delete this PR and you could drop that at same time as your next "letter" update

**Comment by FrankMittelbach** [comment]
Ok I do it WTH the next batch after you fix my mistakes in I to M

**Comment by davidcarlisle** [comment]
package entry will be dropped

**Pull request closed without merging**
