### PR TITLE
add metalogo and metalogox compatibility

### PR DESCRIPTION
**Pull request by mbertucci47**
Lists [metalogo](https://www.ctan.org/pkg/metalogo) and [metalogox](https://www.ctan.org/pkg/metalogox) as compatible and adds tests.

### CODE REVIEW

**Review by FrankMittelbach — COMMENTED** [review]
I might be mistaken, but I think those have to be partially compatible, because, logos like LaTeX or LuaTeX etc should really be tagged with some actualtext to take out the weirdness of the normal TeX related logoes.

By the way do we do that yet for the basic logoes?

**Comment by mbertucci47** [comment]
Ah I was assuming the behavior of the default `\LaTeX` etc. was correct. Will fix

**Comment by u-fischer** [comment]
partially compatible. They inherit in part from our tagging of TeX and LaTeX, but e.g. `\LaTeXe` copy and paste as `LaTeXLATEX2ε` which is clearly wrong.

**Comment by mbertucci47** [comment]
There's a few odd things with copy/paste. If you copy just one line from the following document you get something reasonable, but if you copy both lines you get
```
LaTeX
LaTeX
LATEX2ε
```
```tex
\DocumentMetadata
  {
    lang=en-US,
    pdfversion=2.0,
    pdfstandard=ua-2,
    testphase={phase-III,math,title,table,firstaid},
  }
\documentclass{article}
\begin{document}
\LaTeX

\LaTeXe
\end{document}
```
If they're both `\LaTeXe` you get
```
LATEX2ε
LaTeX
LATEX2ε
```
That's with luatex. With pdftex I get the same thing but with no line breaks or spaces.

**Pull request merged**
